- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS

- ros_topic_name: rplidar/scan
  gz_topic_name: /rplidar/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS

- ros_topic_name: zed2i/rgb/image_rect_color
  gz_topic_name: /zed2i/rgb/image_rect_color
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS

- ros_topic_name: zed2i/rgb/camera_info
  gz_topic_name: /zed2i/rgb/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS

- ros_topic_name: zed2i/depth/depth_registered
  gz_topic_name: /zed2i/depth/depth_registered
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS

- ros_topic_name: zed2i/depth/camera_info
  gz_topic_name: /zed2i/depth/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS

- ros_topic_name: zed2i/points
  gz_topic_name: /zed2i/depth/depth_registered/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS

- ros_topic_name: zed2i/imu/data
  gz_topic_name: /zed2i/imu/data
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS