# rover_sim/parameters/controller.yaml
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    swerve_controller:
      type: rover_controller/RoverSwerveController

    odometry_controller:
      type: rover_controller/RoverOdometryController

    diff_bar_effort_controller:
      type: rover_sim/RockerDiffController

swerve_controller:
  ros__parameters:
    drive_joint_names:
      - fl_wheel_joint
      - fr_wheel_joint
      - bl_wheel_joint
      - br_wheel_joint
    steer_joint_names:
      - fl_wheel_mount_joint
      - fr_wheel_mount_joint
      - bl_wheel_mount_joint
      - br_wheel_mount_joint

    max_linear_speed:  1.0
    max_angular_speed: 1.0
    max_accel:         0.3
    max_decel:         0.6
    cmd_vel_timeout_s: 0.5

    max_steer_deg: 90.0
    max_steer_rate_deg: 90.0 

odometry_controller:
  ros__parameters:
    odom_topic: "/wheels/odom"
    wheelbase: 0.842
    track_width: 0.689
    wheel_radius: 0.15
    steer_joint_names:
      - fl_wheel_mount_joint
      - fr_wheel_mount_joint
      - bl_wheel_mount_joint
      - br_wheel_mount_joint
    drive_joint_names:
      - fl_wheel_joint
      - fr_wheel_joint
      - bl_wheel_joint
      - br_wheel_joint

diff_bar_effort_controller:
  ros__parameters:
    k_stiffness: 2000.0
    d_damping: 10.0
    effort_limit: 150.0
