/camera/usb_cam:
  ros__parameters:
    video_device: /dev/video0
    image_width: 640
    image_height: 480
    framerate: 30.0
    pixel_format: yuyv2rgb
    io_method: mmap
    camera_name: laptop_camera
    frame_id: camera