joystick_interpreter:
  ros__parameters:
    axis_linear:
      x: 1 # Left stick vertical (forward/backward)
      y: 0 # Left stick horizontal (strafing left/right)
    scale_linear:
      x: 1.0
      y: 1.0

    # --- ANGULAR CONTROLS (Right Stick) ---
    axis_angular:
      yaw: 2 # Right stick horizontal (rotation clockwise/counterclockwise)
    scale_angular:
      yaw: 1.0
    
    # --- GRANNY MODE ---
    granny_speed_scale: 0.1
    granny_button: 0

    # --- VY (strafing) ---
    vy_enabled_default: false
    vy_toggle_button: 4   # Share button

    # --- MOTORS / COMPACT MODE ---
    motor_toggle_button: 6   # Options button
    compact_mode_button: 1

    active_toggle_button: 2
    active_default: true

    # --- TIMEOUT / PUBLISH RATE ---
    cmd_timeout: 0.2
    timeout_pub_rate: 20.0
    initial_timed_out: true
    cmd_pub_rate: 20.0

    # --- LIGHTS ---
    spotlight_button: 9   # L1
    beautiful_button: 10   # R1

    # --- TRAFFIC LIGHT ---
    traffic_red_button: 11      # ←
    traffic_yellow_button: 12   # →
    traffic_green_button: 13    # ↑
    traffic_blue_button: 14     # ↓
