<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rover_sensors</name>
  <version>0.0.0</version>
  <description>
    Perception interface and hardware bringup for the Indomitus Rover. This package
    handles the configuration, calibration, and data stream management for the
    rover's suite of environmental sensors and perception hardware.
  </description>
  <maintainer email="bohdan.zasymovych@gmail.com">BohdanZasymovych</maintainer>
  <maintainer email="yagodanr@gmail.com">YahodaMykyta</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>sllidar_ros2</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
