services:
  rover_prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
      args:
        ROS_DISTRO: humble

    image: ${IMAGE_NAME:-ghcr.io/ucuspacerobotics/indomitus-rover-core}:${IMAGE_TAG:-local-prod}
    container_name: rover_prod
    runtime: nvidia
    command: tail -f /dev/null # command: autolaunch
    network_mode: host
    privileged: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    device_cgroup_rules:
      - "c 13:* rmw"
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'source /opt/ros/$$ROS_DISTRO/setup.bash && ros2 pkg list > /dev/null'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=0
      - SDL_VIDEODRIVER=dummy
      - SDL_AUDIODRIVER=dummy
    volumes:
      - /home/indomitus-rover/indomitus-rover-core/src:/opt/ws/src:rw
      - /run/udev:/run/udev:ro