version: '3.8'

services:
  indomitus_rover_dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
      args:
        ROS_DISTRO: humble
        INSTALL_SIM_TOOLS: "false"
    image: indomitus-rover:humble-dev
    container_name: indomitus_rover_dev
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=0
      - CAN_INTERFACE=can0
      - CAN_BITRATE=1000000
      - CAN_TRANSMIT_QUEUE_SIZE=1000
    devices:
      - /dev/input:/dev/input
    volumes:
      - ./:/work:rw
      - ./src:/opt/ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw