services:
  rover_dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
      args:
        BASE_IMAGE: ${BASE_IMAGE_DEV:-stereolabs/zed:5.4-gl-devel-cuda12.1-ubuntu22.04} # Image for the x86-64 architecture
        TARGET_ROS_DISTRO: ${TARGET_ROS_DISTRO:-humble}
        INSTALL_SIM_TOOLS: "false"
    image: ${IMAGE_NAME:-ghcr.io/ucuspacerobotics/indomitus-rover-core}:${IMAGE_TAG:-local-dev}
    container_name: rover_dev
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    device_cgroup_rules:
      - "c 13:* rmw"
    stdin_open: true
    tty: true
    healthcheck:
          test: ["CMD-SHELL", "bash -c 'source /opt/ros/$$ROS_DISTRO/setup.bash && ros2 pkg list > /dev/null'"]
          interval: 10s
          timeout: 5s
          retries: 3
          start_period: 5s
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-42}
      - ROS_LOCALHOST_ONLY=0
      - CAN_INTERFACE=can0
      - CAN_BITRATE=1000000
      - CAN_TRANSMIT_QUEUE_SIZE=1000
      - SDL_VIDEODRIVER=dummy
      - SDL_AUDIODRIVER=dummy
    volumes:
      - ./:/work:rw
      - ./src:/opt/ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/input:/dev/input:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]