controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    steering_controller:
      type: forward_command_controller/ForwardCommandController

    drive_controller:
      type: velocity_controllers/JointGroupVelocityController

    r_rocker_position_controller:
      type: forward_command_controller/ForwardCommandController

steering_controller:
  ros__parameters:
    joints:
      - fl_wheel_mount_joint
      - fr_wheel_mount_joint
      - bl_wheel_mount_joint
      - br_wheel_mount_joint
    interface_name: position

drive_controller:
  ros__parameters:
    joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - bl_wheel_joint
      - br_wheel_joint

r_rocker_position_controller:
  ros__parameters:
    joints:
      - r_rocker_joint
    interface_name: position