# rover_sim/parameters/ros2_control.yaml
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    swerve_controller:
      type: rover_chassis_controller/RoverSwerveController

swerve_controller:
  ros__parameters:
    drive_joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - bl_wheel_joint
      - br_wheel_joint
    steering_joints:
      - fl_wheel_mount_joint
      - fr_wheel_mount_joint
      - bl_wheel_mount_joint
      - br_wheel_mount_joint

    max_linear_speed:  1.0
    max_angular_speed: 1.0
    max_accel:         0.3
    max_decel:         0.6
    cmd_vel_timeout_s: 0.5

    max_steer_deg: 90.0
    max_steer_rate_deg: 45.0 
