controller_manager:
  ros__parameters:
    update_rate: 100  # Hz - frequency of main loop

    hardware_components_initial_state:
      inactive:
        - RoverHardware

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    swerve_controller:
      type: rover_controller/RoverSwerveController
    
    odometry_controller:
      type: rover_controller/RoverOdometryController

swerve_controller:
  ros__parameters:
    drive_joint_names:
      - fl_wheel_joint
      - fr_wheel_joint
      - bl_wheel_joint
      - br_wheel_joint
    steer_joint_names:
      - fl_wheel_mount_joint
      - fr_wheel_mount_joint
      - bl_wheel_mount_joint
      - br_wheel_mount_joint

    # Dynamics
    max_accel: 0.3
    max_decel: 0.6
    cmd_vel_timeout_s: 0.5

    # Kinematics restriction
    max_steer_deg: 90.0
    max_steer_rate_deg: 120.0 # degrees/s
    max_linear_speed:  1.0
    max_angular_speed: 1.0

    # Geometry
    wheelbase:     0.842   # meters, front-to-rear axle distance
    track_width:   0.682   # meters, left-to-right wheel distance
    wheel_radius:  0.16   # meters

odometry_controller:
  ros__parameters:
    wheelbase:    0.842
    track_width:  0.682
    wheel_radius: 0.16
    steer_joint_names:
      - fl_wheel_mount_joint
      - fr_wheel_mount_joint
      - bl_wheel_mount_joint
      - br_wheel_mount_joint
    drive_joint_names:
      - fl_wheel_joint
      - fr_wheel_joint
      - bl_wheel_joint
      - br_wheel_joint
