joystick_interpreter:
  ros__parameters:
    axis_linear:
      x: 1 # Left stick vertical (forward/backward)
      y: 0 # Left stick horizontal (strafing left/right)
    scale_linear:
      x: 0.5
      y: 0.5

    # --- ANGULAR CONTROLS (Right Stick) ---
    axis_angular:
      yaw: 2 # Right stick horizontal (rotation clockwise/counterclockwise)
    scale_angular:
      yaw: 1.0

    vy_toggle_button: 4 # Share button
    motor_toggle_button: 6 # Options button
    vy_enabled_default: false
    cmd_timeout: 0.5
    timeout_pub_rate: 10.0
    initial_timed_out: true
    compact_mode_button: 1

    cmd_pub_rate: 20.0