teleop_node:
  ros__parameters:
    require_enable_button: false

    # --- LINEAR CONTROLS (Left Stick) ---
    axis_linear:
      x: 1 # Left stick vertical (forward/backward)
      y: 0 # Left stick horizontal (strafing left/right)
    scale_linear:
      x: 0.5
      y: 0.5

    # --- ANGULAR CONTROLS (Right Stick) ---
    axis_angular:
      yaw: 2 # Right stick horizontal (rotation clockwise/counterclockwise). 3 for ubuntu 22.04, 2 for ubuntu 24.04
    scale_angular:
      yaw: 1.0

joystick_interpreter:
  ros__parameters:
    # --- LINEAR CONTROLS (Left Stick) ---
    axis_linear_x: 1
    axis_linear_y: 0
    scale_linear_x: 0.5
    scale_linear_y: 0.5

    # --- ANGULAR CONTROLS (Right Stick) ---
    axis_angular_yaw: 2
    scale_angular_yaw: 1.0

    vy_toggle_button: 4      # Share button
    motor_toggle_button: 6   # Options button
    compact_mode_button: 1   # B button
    vy_enabled_default: false