# rover_bringup/config/twist_mux.yaml
twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic:   "cmd_vel_joy"
        timeout: 0.5
        priority: 100
      
      recovery:
        topic:   "cmd_vel_recovery"
        timeout: 1.0
        priority: 75
      
      nav2:
        topic:   "cmd_vel_nav"
        timeout: 1.0
        priority: 50

      external:
        topic:   "cmd_vel_ext"
        timeout: 0.5
        priority: 10 
