container_can_node:
  ros__parameters:

    can:
      # CAN ID for sening commands to ESP32
      cmd_id: 0x200

      # CAN ID for responses from ESP32
      lid_resp_id:    0x201
      weight_resp_id: 0x202

      # Commands
      cmd_open:         0x01
      cmd_close:        0x02
      cmd_poll_status:  0x04  # polling status lid open/close
      cmd_get_weight:   0x10

      # Status responses from ESP32
      status_ack:       0x00  # command accepted, action started
      status_in_progress: 0x01
      status_done:      0x02
      status_error:     0x03

    timeouts: # in seconds
      lid_ack_s:    2.0
      lid_done_s:   15.0
      lid_poll_interval_s: 0.5
      weight_s: 3.0