teleop_node:
  ros__parameters:
    require_enable_button: false

    # --- LINEAR CONTROLS (Left Stick) ---
    axis_linear:
      x: 1 # Left stick vertical (forward/backward)
      y: 0 # Left stick horizontal (strafing left/right)
    scale_linear:
      x: 1
      y: 1

    # --- ANGULAR CONTROLS (Right Stick) ---
    axis_angular:
      yaw: 2 # Right stick horizontal (rotation clockwise/counterclockwise). 2 for ubuntu 22.04, 3 for ubuntu 24.04
    scale_angular:
      yaw: 1.0