rover_controller:
  ros__parameters:

    # Maximum translational speed (m/s)
    max_linear_speed: 1.0

    # Maximum rotational speed (rad/s)
    max_angular_speed: 1.0

    # Linear acceleration limit (m/s²)
    max_accel: 0.3
    max_decel: 0.6

    # Control loop frequency (Hz)
    control_frequency: 20.0

    cmd_vel_timeout_s: 0.5