name: Build

on:
  push:
    branches:
      - main
      - develop
      - feature/shared/workflow-ci-fix

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble-ros-base
    steps:
      - uses: actions/checkout@v4

      - name: Cache apt packages
        shell: bash
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-${{ hashFiles('**/package.xml') }}

      - name: Install dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build