name: Build

on:
  push:
    branches:
      - main
      - develop
      - feature/shared/workflow-ci

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup ROS2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt update
          sudo apt install -y can-utils iproute2
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --packages-ignore rover_sim