name: Cleanup Untagged GHCR Images

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Delete untagged images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account-type: org
          image-names: ${{ github.event.repository.name }}
          image-tags: "!*" # Targets only images without tags
          cut-off: 3 days ago
          token: ${{ secrets.GITHUB_TOKEN }}