name: GHCR Garbage Collector

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  clean-ghcr:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Lowercase Repository Name
        id: lowercase-repo
        run: |
          REPO="${{ github.event.repository.name }}"
          echo "name=${REPO,,}" >> $GITHUB_OUTPUT

      - name: Clean stale DEV SHA tags
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: ${{ steps.lowercase-repo.outputs.name }}
          image-tags: "sha-*-dev"
          cut-off: 14 days ago UTC
          keep-n-most-recent: 5
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean stale PROD SHA tags
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: ${{ steps.lowercase-repo.outputs.name }}
          image-tags: "sha-*-prod"
          cut-off: 30 days ago UTC
          keep-n-most-recent: 10
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete untagged images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: ${{ steps.lowercase-repo.outputs.name }}
          image-tags: "!*"
          cut-off: 3 days ago UTC 
          token: ${{ secrets.GITHUB_TOKEN }}